"""Centralized prompt templates for every assistant capability.

Keeping every prompt in one place makes the system auditable: a
reviewer (or a teammate) can see exactly what instructions the model
is given, without hunting through UI code. Every prompt enforces the
same non-negotiable ground rules:

1. Answer only from the supplied document(s)/context - no fabrication.
2. Use plain, accessible language (aim for a general-reader level).
3. Never present output as formal legal advice; always frame it as
   general information and point toward professional review for
   anything consequential.
"""

from __future__ import annotations

SYSTEM_PROMPT = """You are a Legal Document Assistant. Your job is to help \
everyday people (tenants, freelancers, employees, small business owners, \
consumers) understand legal documents and information they provide to you.

Ground rules you must always follow:
- Base every answer strictly on the document(s) or context the user gives \
you. If something isn't in the document, say so plainly instead of \
guessing or inventing clauses, numbers, or obligations.
- Write in clear, plain language. Avoid legal jargon; when a legal term is \
unavoidable, briefly explain what it means in everyday words.
- You provide general legal information and education, NOT formal legal \
advice, and you are not a substitute for a licensed attorney. Never tell \
the user what they definitely should or must legally do in their specific \
situation - instead explain their apparent options, likely implications, \
and when speaking to a qualified professional would be wise.
- Be balanced: point out both protective and risky/unusual terms. Do not \
alarm the user unnecessarily, but do not downplay genuine risks either.
- If the document is ambiguous, incomplete, or contradictory, say so \
explicitly rather than resolving the ambiguity yourself.
- Never fabricate a citation, statute, case, or clause number that is not \
actually present in the supplied text.
"""

DISCLAIMER = (
    "\u26a0\ufe0f This is general information generated by an AI assistant, "
    "not legal advice. For decisions with real financial, legal, or "
    "personal consequences, please consult a licensed attorney."
)


def build_simplify_prompt(document_text: str) -> str:
    return f"""Simplify the following legal document for a general reader \
with no legal background.

Produce:
1. A 3-5 sentence plain-language overview of what this document is and \
what it's for.
2. A section-by-section (or clause-by-clause) breakdown, each explained in \
1-3 plain sentences.
3. A short glossary of any unavoidable legal/technical terms used.

DOCUMENT:
---
{document_text}
---
"""


def build_risk_clause_prompt(document_text: str) -> str:
    return f"""Review the following legal document and identify clauses \
that are important for the signer to notice.

Organize your answer into three clearly labeled groups:
- HIGH ATTENTION: clauses that create significant obligations, risk, \
liability, penalties, automatic renewals, waivers of rights, or unusual/ \
one-sided terms.
- STANDARD OBLIGATIONS: normal duties or commitments this document creates \
for each party.
- PROTECTIVE / FAVORABLE TERMS: clauses that protect or benefit the reader.

For each clause, quote or reference which part of the document it comes \
from, and explain in plain language why it matters.

DOCUMENT:
---
{document_text}
---
"""


def build_compare_prompt(document_a: str, document_b: str,
                          label_a: str = "Document A",
                          label_b: str = "Document B") -> str:
    return f"""Compare the two legal documents below and produce:
1. A short summary of what each document is.
2. A side-by-side comparison of key terms that appear in both (e.g. \
duration/term, payment/fees, termination conditions, liability, \
confidentiality, renewal terms) - only compare terms that are actually \
present.
3. A list of MATERIAL DIFFERENCES that could matter to the reader, ranked \
roughly by importance.
4. A list of any inconsistencies or contradictions, if you find one \
document conflicts with typical expectations set by the other.

{label_a}:
---
{document_a}
---

{label_b}:
---
{document_b}
---
"""


def build_qa_prompt(document_text: str, question: str,
                     chat_history: str = "") -> str:
    history_block = f"\nPrior conversation so far:\n{chat_history}\n" if chat_history else ""
    return f"""Using ONLY the document text below, answer the user's \
question. If the answer is not addressed in the document, say clearly \
that the document does not cover it - do not guess.
{history_block}
DOCUMENT:
---
{document_text}
---

QUESTION: {question}
"""


def build_checklist_prompt(document_text: str) -> str:
    return f"""Based on the following legal document, produce an \
actionable checklist for the reader, organized as:
1. BEFORE SIGNING - things to verify, clarify, or negotiate.
2. AFTER SIGNING - dates, deadlines, or actions the reader is now \
responsible for (e.g. payment dates, renewal notice windows, filing \
deadlines).
3. RED FLAGS TO DOUBLE-CHECK WITH A PROFESSIONAL - anything unusual, \
high-stakes, or unclear enough that a lawyer's review is genuinely worth \
the cost.

Use short, concrete checklist items (checkbox style), not paragraphs.

DOCUMENT:
---
{document_text}
---
"""


def build_lawyer_prep_prompt(document_text: str, user_context: str = "") -> str:
    context_block = f"\nAdditional context from the user about their situation:\n{user_context}\n" if user_context else ""
    return f"""The user wants to bring this document to a lawyer for a \
paid consultation and wants to prepare so the meeting is efficient.
{context_block}
Based on the document, produce:
1. A one-paragraph plain-language summary of the document to give the \
lawyer for quick context.
2. A prioritized list of specific, well-formed questions the user should \
ask the lawyer, focused on the clauses that are ambiguous, risky, or \
unusual.
3. A short list of documents/information the user should bring or gather \
beforehand (e.g. related correspondence, prior agreements, ID, receipts) \
based on what this document references.

DOCUMENT:
---
{document_text}
---
"""
